package representation;

import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;

/**
 * Created by user on 1/7/17.
 */
public class Javalang {
    static final String OUTPUT_DIRECTORY = "/home/user/Desktop/java-autogenerated-interpreter";

    public static void main(String[] args) throws IOException {
        createProjectStub();
        createTranslator();
    }

    public static void createProjectStub() throws IOException {
        FileUtils.deleteDirectory(new File(OUTPUT_DIRECTORY));
        new File(OUTPUT_DIRECTORY).mkdirs();
        new File(OUTPUT_DIRECTORY + "/src/main/java").mkdirs();
        FileUtils.copyFile(
                new File("./src/main/resources/representation/Main.java.template"),
                new File(OUTPUT_DIRECTORY + "/src/main/java/Main.java"));
        FileUtils.copyFile(
                new File("./src/main/resources/representation/pom.xml.template"),
                new File(OUTPUT_DIRECTORY + "/pom.xml"));
    }

    public static void createTranslator() throws IOException {
        FileUtils.copyFile(
                new File("./src/main/resources/representation/Token.java.template"),
                new File(OUTPUT_DIRECTORY + "/src/main/java/Token.java"));
    }
}
